# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: spanjaan.bloghub::lang.model.comments.recordName

# Model Form Field configuration
form: $/spanjaan/bloghub/models/comment/fields.yaml

# Model Class name
modelClass: Spanjaan\BlogHub\Models\Comment

# Default redirect location
defaultRedirect: spanjaan/bloghub/comments

# Create page
create:
    title: backend::lang.form.create_title
    redirect: spanjaan/bloghub/comments/update/:id
    redirectClose: spanjaan/bloghub/comments

# Update page
update:
    title: backend::lang.form.update_title
    redirect: spanjaan/bloghub/comments
    redirectClose: spanjaan/bloghub/comments

# Preview page
preview:
    title: backend::lang.form.preview_title
