# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: spanjaan.bloghub::lang.model.tags.recordName

# Model Form Field configuration
form: $/spanjaan/bloghub/models/tag/fields.yaml

# Model Class name
modelClass: Spanjaan\BlogHub\Models\Tag

# Default redirect location
defaultRedirect: spanjaan/bloghub/tags

# Create page
create:
    title: backend::lang.form.create_title
    redirect: spanjaan/bloghub/tags/update/:id
    redirectClose: spanjaan/bloghub/tags

# Update page
update:
    title: backend::lang.form.update_title
    redirect: spanjaan/bloghub/tags
    redirectClose: spanjaan/bloghub/tags

# Preview page
preview:
    title: backend::lang.form.preview_title
